parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Resolver\ValidatedApiRequestResolver:
      tags: [ 'controller.argument_value_resolver' ]

    App\EventListener\ValidationExceptionListener:
      tags:
          - { name: kernel.event_listener, event: kernel.exception }